name: berries
channels:
  - pytorch
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.7.0
  - torchaudio=0.7.0
  - torchvision=0.8.1
  - cudatoolkit=11.0
  - yapf=0.30.0
  - pandas=1.1.3
  - pyyaml=5.3.1
  - matplotlib=3.3.3
  - scikit-learn=0.23.2
  - plotly=4.12.0
  - tqdm=4.51.0
  - xlrd
  - neptune-client
  - psutil

