
# PR curves for regression and classification with 2 class
plt.figure()
prec_recall_curve_class2 = sklearn.metrics.precision_recall_curve(pred_class2['Act0'].values, pred_class2['Pred0'].values)
prec_recall_curve_reg2 = sklearn.metrics.precision_recall_curve(pred_regr['Actual'].values > 0, (pred_regr['Prediction'].values + 1) / 2)
plt.plot(prec_recall_curve_class2[1], prec_recall_curve_class2[0], label = "Classification")
plt.plot(prec_recall_curve_reg2[1], prec_recall_curve_reg2[0], label = "Regression")
plt.title("Precision-Recall Curve for Classification and Regression(Quantized)")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.legend(loc = "upper right")
plt.show()

# PR curves for regression and classification with 3 class
plt.figure()
prec_recall_curve_class3_1 = sklearn.metrics.precision_recall_curve(pred_class3['Act0'].values, pred_class3['Pred0'].values)
prec_recall_curve_class3_2 = sklearn.metrics.precision_recall_curve(pred_class3['Act1'].values, pred_class3['Pred1'].values)
prec_recall_curve_class3_3 = sklearn.metrics.precision_recall_curve(pred_class3['Act2'].values, pred_class3['Pred2'].values)
prec_recall_curve_reg3_1 = sklearn.metrics.precision_recall_curve(pred_regr['Actual'].values < -.38, 1 - ((pred_regr['Prediction'].values + 1) / 2))
prec_recall_curve_reg3_2 = sklearn.metrics.precision_recall_curve(np.logical_and(pred_regr['Actual'].values > -.38, pred_regr['Actual'].values < .38), 1 - abs(pred_regr['Prediction'].values))
prec_recall_curve_reg3_3 = sklearn.metrics.precision_recall_curve(pred_regr['Actual'].values > .38, (pred_regr['Prediction'].values + 1) / 2)
plt.plot(prec_recall_curve_class3_1[1], prec_recall_curve_class3_1[0], label = "Class 1 vs all")
plt.plot(prec_recall_curve_class3_2[1], prec_recall_curve_class3_2[0], label = "Class 2 vs all")
plt.plot(prec_recall_curve_class3_3[1], prec_recall_curve_class3_3[0], label = "Class 3 vs all")
plt.plot(prec_recall_curve_reg3_1[1], prec_recall_curve_reg3_1[0], label = "Class 1 vs all (regression)")
plt.plot(prec_recall_curve_reg3_2[1], prec_recall_curve_reg3_2[0], label = "Class 2 vs all (regression)")
plt.plot(prec_recall_curve_reg3_3[1], prec_recall_curve_reg3_3[0], label = "Class 3 vs all (regression)")
plt.title("Precision-Recall Curve for Classification and Regression(Quantized) with 3 Class")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.legend(loc = "upper right")
plt.show()

# ROC curves for regression and classification with 2 class
plt.figure()
roc_curve_class2 = sklearn.metrics.roc_curve(pred_class2['Act0'].values, pred_class2['Pred0'].values)
roc_curve_reg2 = sklearn.metrics.roc_curve(pred_regr['Actual'].values > 0, (pred_regr['Prediction'].values + 1) / 2)
plt.plot(roc_curve_class2[0], roc_curve_class2[1], label = "Classification")
plt.plot(roc_curve_reg2[0], roc_curve_reg2[1], label = "Regression")
plt.title("ROC Curve for Classification and Regression(Quantized)")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.legend(loc = "upper right")
plt.show()

# ROC curves for regression and classification with 3 class
plt.figure()
roc_curve_class3_1 = sklearn.metrics.roc_curve(pred_class3['Act0'].values, pred_class3['Pred0'].values)
roc_curve_class3_2 = sklearn.metrics.roc_curve(pred_class3['Act1'].values, pred_class3['Pred1'].values)
roc_curve_class3_3 = sklearn.metrics.roc_curve(pred_class3['Act2'].values, pred_class3['Pred2'].values)
roc_curve_reg3_1 = sklearn.metrics.roc_curve(pred_regr['Actual'].values < -.38, 1 - ((pred_regr['Prediction'].values + 1) / 2))
roc_curve_reg3_2 = sklearn.metrics.roc_curve(np.logical_and(pred_regr['Actual'].values > -.38, pred_regr['Actual'].values < .38), 1 - abs(pred_regr['Prediction'].values))
roc_curve_reg3_3 = sklearn.metrics.roc_curve(pred_regr['Actual'].values > .38, (pred_regr['Prediction'].values + 1) / 2)
plt.plot(roc_curve_class3_1[0], roc_curve_class3_1[1], label = "Class 1 vs all")
plt.plot(roc_curve_class3_2[0], roc_curve_class3_2[1], label = "Class 2 vs all")
plt.plot(roc_curve_class3_3[0], roc_curve_class3_3[1], label = "Class 3 vs all")
plt.plot(roc_curve_reg3_1[0], roc_curve_reg3_1[1], label = "Class 1 vs all (regression)")
plt.plot(roc_curve_reg3_2[0], roc_curve_reg3_2[1], label = "Class 2 vs all (regression)")
plt.plot(roc_curve_reg3_3[0], roc_curve_reg3_3[1], label = "Class 3 vs all (regression)")
plt.title("ROC Curve for Classification and Regression(Quantized) with 3 Class")
plt.xlabel("FPR")
plt.ylabel("TPR")
plt.legend(loc = "upper right")
plt.show()
